services:
  app:
    build: .
    image: test
    container_name: financial_news_collectors
    volumes:
      - /home/daniel/Desktop/test/financial_news_collectors:/usr/src/app/downloads
    ports:
      - "8102:80"
    expose:
      - "8102"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  selenium_standalone_chrome:
    image: selenium/standalone-chrome # For running on non-Raspberry systems (non-ARM)
    #image: seleniarm/standalone-chromium:latest # For running on Raspberry systems (ARM)
   
    container_name: selenium_standalone_chrome_financial_news_collectors
    privileged: true
    shm_size: 2g

  #db:
  #  image: postgres
  #  restart: always
  #  environment:
  #    POSTGRES_USER: airflow
  #    POSTGRES_PASSWORD: airflow